FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_VERSION \
           postgresql-client-$PG_VERSION \
           postgresql-contrib-$PG_VERSION \
           postgresql-$PG_VERSION-plv8 \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/* \
      && rm -rf /tmp/*
COPY docker-entrypoint.sh /usr/local/bin/

RUN rm -rf "$PG_BASE" && mkdir -p "$PG_BASE" && chown -R postgres:postgres "$PG_BASE" \
      && mkdir -p /var/run/postgresql/$PG_VERSION-main.pg_stat_tmp \
      && chown -R postgres:postgres /var/run/postgresql && chmod g+s /var/run/postgresql \
      && chmod +x /usr/local/bin/docker-entrypoint.sh

RUN echo "host all  all    0.0.0.0/0  md5" >> $PG_CONFIG_DIR/pg_hba.conf \
      && echo "host all  all    ::/0  md5" >> $PG_CONFIG_DIR/pg_hba.conf \
      && echo "listen_addresses='*'" >> $PG_CONFIG_FILE

USER postgres
ENV PATH $PATH:/usr/lib/postgresql/$PG_VERSION/bin
VOLUME ["${PG_BASE}"]

EXPOSE 5432

WORKDIR /PostgreSQL
ADD . /PostgreSQL

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["psql", "-U", "postgres", "-f", "schema.sql", "-p", "5432", "postgres"]
