version: "2"
services:
  db:
    image: postgres1
    environment:
      POSTGRES_USER: postgres

  web:
    build: ./NGINX/Dockerfile
    ports:
     - "6060:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - app

  app:
    image: goapp1
    depends_on:
      - db
