version: "2.1"
services:
  db:
    build: ./PostgreSQL
    environment:
      POSTGRES_USER: postgres
    expose:
      - "5432"
    volumes:
      # Persist the data between container invocations
      - postgresVolume:/var/lib/postgresql/data
      - ./logs:/logs

  web:
    build: ./NGINX
    ports:
      - "6060:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app

  app:
    build: ./GOApplication
    expose:
      - "8080"
    depends_on:
      - db
    command: ["wait-for-postgres.sh", "db", "go", "test", "./GOApplication"]
volumes:
  postgresVolume:
