version: "2"
services:
  db:
    image: postgres1
    environment:
      POSTGRES_USER: postgres

  web:
    image: nginx1
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - "6060:80"
    environment:
     - NGINX_PORT=80
    command: /bin/bash -c "./NGINX/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - app

  app:
    image: goapp1
    depends_on:
      - db
