version: "2.1"
services:
  db:
    build: ./PostgreSQL
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    expose:
      - "5432"
    volumes:
      # Persist the data between container invocations
      - postgresVolume:/var/lib/postgresql/data
      - ./logs:/logs

  web:
    build: ./NGINX
    ports:
      - "6060:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app

  app:
    build: ./GOApplication
    depends_on:
      - db
volumes:
  postgresVolume:
